### ISSUE TITLE
Poor justification

### ISSUE THREAD

**Issue by fcntl** [keraf/NoCoin#10]
> the user should have the choice to opt-in 

Visiting a website is already an opt-in action. If you don't like it, don't go there!

**Comment by devsnek** [comment]
i would disagree with that, a user visiting a website doesn't know what content that website might hold.

**Comment by keraf** [comment]
I agree with @devsnek, you can't know what's on a site before going on it. Additionally, a user should have the choice on whether he wants to run something on his machine as much as webmasters have the choice to not serve him content if he refuses to mine coins. Anti-No Coin someone? 😄 

Closing the issue.
