### ISSUE TITLE
Cryptojacking Script Found in Live Help Widget, Impacts Around 1,500 Sites

### ISSUE THREAD

**Issue by ZeroDot1** [keraf/NoCoin#103]
https://www.bleepingcomputer.com/news/security/cryptojacking-script-found-in-live-help-widget-impacts-around-1-500-sites/ 
`http://www.livehelpnow.net/lhn/widgets/helpouttab/lhnhelpouttab-current.min.js`

**Comment by keraf** [comment]
Fixed by the website owner.
