### ISSUE TITLE
Coinbase 

### ISSUE THREAD

**Issue by max11212** [keraf/NoCoin#105]
No coin 0.48 active on www.coinbase.com create errors 
It' only incompatibilty or they have some mining script hidden on site ?
![schermata 2017-11-29 alle 15 32 37](https://user-images.githubusercontent.com/34099128/33380348-0f980f6a-d51b-11e7-86e9-f645093f9205.png)
![schermata 2017-11-29 alle 15 29 47](https://user-images.githubusercontent.com/34099128/33380352-11534b94-d51b-11e7-9b0f-fbc54f9b7153.png)

**Comment by keraf** [comment]
Are you sure this is caused by No Coin? I just tested the website and everything works fine for me. Might be another extension. Try disabling them one by one to see which extension is causing you issues.
