### ISSUE TITLE
Add aservices.party to blocklist

### ISSUE THREAD

**Issue by quidsup** [keraf/NoCoin#109]
Recently registered domain aservices.party is used for purposes of browser based coin mining and could do with adding to the blocklist

Thanks

**Comment by Firminator** [comment]
source?
sites that use it (publicwww shows 0 results for "aservices.party")

**Comment by keraf** [comment]
Don't see any mining happening while on the website or anything related to browser mining. Could you point me to what makes you believe that this should be added to the blacklist?

**Comment by quidsup** [comment]
Looks like it was a fast flux type domain, no longer being used now
