### ISSUE TITLE
Not work on nahnoji.cz

### ISSUE THREAD

**Issue by Weafyr** [keraf/NoCoin#114]
view-source:http://nahnoji.cz/embed?id=4700

**Comment by jvaca4th** [comment]
Another one mining Sumo: http://www.goredirect.party/s/?ov=1&utm_source=adsterra&utm_campaign=adsterra-ww-win10_selected&utm_term=44577

**Comment by Firminator** [comment]
Keraf, you might want to replace goredirect.party/s/* with goredirect.party/assets/* as they are loading the wasm from http://www.goredirect.party/assets/c.201803000000.js whch spikes CPU to 100%.

**Comment by keraf** [comment]
@Firminator Good spot, I'll reopen this issue and fix this today. Cheers!
