### ISSUE TITLE
Block a website 

### ISSUE THREAD

**Issue by Blessik** [keraf/NoCoin#128]
Can you block website https://a-o.ninja/ ?
This website was already blocked, but they got new script.

**Comment by keraf** [comment]
Thanks for reporting this website. The mining script has been added to the blacklist.

**Comment by Firminator** [comment]
gasolina.ml
a-o.ninja/apk-AO/kingofthenorth/

**Comment by Firminator** [comment]
Keraf,
FYI I just cross-referenced the additions to the blacklist for search prurposes. You added the domains already to the list. Issues can be closed.
