### ISSUE TITLE
Does not seem to work on Firefox?

### ISSUE THREAD

**Issue by gradinaruvasile** [keraf/NoCoin#131]
Tried 2 sites with :

https://coinhive.com/
https://www.2giga.link/

Both were mining succesfully. Linux 64 bit, Firefox 57.0.4

**Comment by AliIsingor** [comment]
It seems not working for me too...

Ubuntu 17.10.1, Firefox 57.0.4

**Comment by keraf** [comment]
2giga.link changed their mining script not long ago. I added it for the next patch release coming today or tomorrow. 

The miner on Coin Hive though isn't blocked as it is using authedmine which No Coin is currently not blocking (see #67 ).

**Comment by keraf** [comment]
The miner on 2giga.link is now blocked (see release 0.4.12).

**Comment by brunolemos** [comment]
Just tested https://coinhive.com/ on firefox and it did not block it. CPU went to 100%.
