### ISSUE TITLE
PLease script in blacklist from this website

### ISSUE THREAD

**Issue by recds7** [keraf/NoCoin#139]
http://videostream.dn.ua/videopage/videoPage.php?g=MTY5OTM%E2%84%96f&c=es&i=eWl2a3Vmb2F1Yg%E2%84%96f%E2%84%96f

Note: Issue after click in any video on this website.

Tks

**Comment by keraf** [comment]
I don't see any mining on there. Could you point me to the mining script?

**Comment by recds7** [comment]
Hello!

The cpu usage increases to 100% a few seconds after clicking in any video
on right side.

It's just an assumption. Many people who work with bets, just like me,
spend many hours on this site. There are lots of advertisements too. But
unfortunately I do not know what part of the script is mining.

Anyway, thanks for the attention and congrats for the work.

Best regards,

Renato Campos da Silva

2018-01-29 22:42 GMT-02:00 Rafael K <notifications@github.com>:

**Comment by Firminator** [comment]
Can't reproduce. Might be a local issue, i.e. the device you are working with temporarily can't handle the load.
