### ISSUE TITLE
What happens if person embeds miner in main javascript

### ISSUE THREAD

**Issue by AhsanE** [keraf/NoCoin#14]
What happens if person embeds miner in main javascript and obfuscates it?

**Comment by keraf** [comment]
Currently it won't block it. The way how the extension works is simply by blacklisting some known miner services. I was looking though into other ways of blocking miners and especially for the use case you're mentioning. But as currently all the miners I have found are services, I guess for now it's going to be the simple blacklist route. I will investigate more when self hosted miner start appearing. Please raise a new issue if you know any.
