### ISSUE TITLE
Miner on page not detected

### ISSUE THREAD

**Issue by JorgeMendozaG** [keraf/NoCoin#140]
Hi!, I just access to this page http://ripplexrp.blog/ripple-the-firm-behind-the-cryptocurrency-xrp-just-added-2-financial-services-firms-to-its-roster-of-clients/ and it looks like they have a miner, and NoCoin won't block  the miner.

**Comment by keraf** [comment]
Thanks for reporting this. I have just added the mining script to the blacklist.

**Comment by Firminator** [comment]
ajplugins.com

keywords:
plugins/ajcryptominer/assets/
/ajcryptominer/
/ajcm-inject

**Comment by keraf** [comment]
@Firminator ?

**Comment by Firminator** [comment]
Same here. Can be closed. Just referencing what has been added.
