### ISSUE TITLE
Protection in this site its not working

### ISSUE THREAD

**Issue by OldMartin** [keraf/NoCoin#141]
Im pretty sure this site have a mining script when i open the site my cpu from 2%to70% usage should be cool check if there a new mining type script 
jkanime.net

**Comment by keraf** [comment]
@OldMartin Don't see any mining on there. Could you point me to what makes you think that there's mining happening on this website?

**Comment by OldMartin** [comment]
@keraf its like youtube but with anime but somehow i get a high cpu i try to open the site only but the cpu load gets high and  i open other sites with the same structure and the cpu its different  stay lower i just suspect have a scrit doing something with the cpu beacause the adblock its working and the site have all the adds blocked and for my pc specs its weird have this cpu for i5 6600k

**Comment by keraf** [comment]
I had a more thorough look again, and even though I saw the tab using a little more CPU than usual, I couldn't find any mining scripts. Can anyone else confirm?

**Comment by Taurean75** [comment]
I didn't find any.

**Comment by keraf** [comment]
@Taurean75 Thanks for the confirmation. Closing this issue.
