### ISSUE TITLE
Miner on https://vbox7-mp3.info/ is not blocked

### ISSUE THREAD

**Issue by marto55555** [keraf/NoCoin#142]
There is a miner on this website: [https://www.vbox7-mp3.info/](https://www.vbox7-mp3.info/)
They seem to be getting the mining JS code from here: [http://webmine.pro/lib/crlt.js](http://webmine.pro/lib/crlt.js)

**Comment by keraf** [comment]
Thanks for reporting this website. The miner is now blocked.
