### ISSUE TITLE
another bitcoin script to block

### ISSUE THREAD

**Issue by mikeymike76** [keraf/NoCoin#148]
Hi,

Installed no coin a while ago and it worked great on this site, my CPU finally quietened down.

But it seems they have updated their script and now its no longer working:
300mbfilms.co

I have had a qucik look through the code with the firefox debugger, but couldn't see any reference to "coin" so can't see the script.

I am sure someone else here is able to find it in the webcode.

Thanks for the great product.

Mike

**Comment by Firminator** [comment]
Thanks for reporting.

PR needs to block:

mutuza.win/processor.js
mutuza.win/worker.js
mutuza.win/lib/*

wss://www.mutuza.win/proxy

**Comment by Firminator** [comment]
https://github.com/keraf/NoCoin/pull/157

**Comment by keraf** [comment]
Blocked with @Firminator 's PR.
