### ISSUE TITLE
l33tsite.info and doubleclick%x%.xyz

### ISSUE THREAD

**Issue by Firminator** [keraf/NoCoin#149]
.l33tsite.info
.doubleclick1.xyz
.doubleclick2.xyz
.doubleclick3.xyz
.doubleclick4.xyz
.doubleclick5.xyz
.doubleclick6.xyz
source: https://blog.trendmicro.com/trendlabs-security-intelligence/malvertising-campaign-abuses-googles-doubleclick-to-deliver-cryptocurrency-miners

The doubleclick domains are not official Google domains, but russian.

**Comment by Firminator** [comment]
*.amazonaws.com/doubleclick13/

**Comment by Firminator** [comment]
https://github.com/keraf/NoCoin/pull/158

Didn't add
.doubleclick1.xyz
.doubleclick2.xyz
.doubleclick3.xyz
.doubleclick4.xyz
.doubleclick5.xyz
.doubleclick6.xyz
as they are just malvertisement domains. The actual mining script is loaded from AmazonAWS and the worker threads are on leet.info

**Comment by keraf** [comment]
Added by your PR, closing issue.
