### ISSUE TITLE
Not blocking Coinhive

### ISSUE THREAD

**Issue by mesolaries** [keraf/NoCoin#152]
I've installed no coin and went to coinhive website to check if no coin is working. But it's not. When I press Start mining button on coinhive it's starting to load my cpu.
I'm using Chrome version 64.

Tested it in Firefox, not working either.

**Comment by Firminator** [comment]
This is called mining with consent. You decide if you press the Mining button or not. NoCoin doesn't block miners that respect user choices. NoCoin only blocks miners that run hidden without asking the user.

In other words: not an issue. Can be closed.
