### ISSUE TITLE
onitube

### ISSUE THREAD

**Issue by rightnoww** [keraf/NoCoin#155]
Since today, february 9, no-coin does not recognise mining at onitube . com ---- it worked very well before -- TNX !

**Comment by Firminator** [comment]
ws://*.monerise.com/proxy/*
wss://*.monerise.com/proxy/*
ws://*.monerise.com:9333/proxy/*
wss://*.monerise.com:9333/proxy/*
*://*.monerise.com/core/*

**Comment by Firminator** [comment]
Monerise.com states:

> CONVERT YOUR USERS INTO PATRONS
> Monetise content by mining CryptoNight coins, tastefully in the background.

**Comment by keraf** [comment]
Thanks for reporting. Should be blocked now.
