### ISSUE TITLE
Better to separate blacklist.txt

### ISSUE THREAD

**Issue by arpitnext** [keraf/NoCoin#16]
I would suggest to separate blacklist.txt as a different project, so that other extensions, apps and services can utilize and integrate it. It would be much easier to update the list too, without updating the NoCoin extension frequently.

**Comment by keraf** [comment]
Thanks for the suggestion, that's a good idea. I'll add that to my priorities.

**Comment by keraf** [comment]
The extension is now loading the blacklist from Github. I have decided not to separate it from the project as the location is not likely to change in the future. I guess if other projects wish to use it, it's fairly safe to point it to: https://raw.githubusercontent.com/keraf/aaaNoCoin/master/src/blacklist.txt

**Comment by suhail-sullad** [comment]
URL returned 404.

**Comment by keraf** [comment]
Good catch, some chars snuck in before my commit. That's fixed now!

**Comment by suhail-sullad** [comment]
Also i think we should add response empty or null check before going into fallback.  Sending a PR now.

**Comment by arpitnext** [comment]
created a [Adblock Plus filter list](https://github.com/arpitnext/NoMiner/blob/master/filters.txt) based on the `blacklist.txt`
