### ISSUE TITLE
Custom blacklists

### ISSUE THREAD

**Issue by 0xBADCA7** [keraf/NoCoin#160]
Please add  a functionality to allow for custom blacklists by extension users. It seems like people raise requests to block one domain or another when they could do it ad-hoc within the extension instead.

**Comment by Firminator** [comment]
Not a big fan of additional features. I'd rather have it super simple. Install and forget. User shouldn't be worrying about adding new blacklists, changing settings, and generally messing with it.

**Comment by zingmars** [comment]
Having 'power user' features does not mean the experience for the average Joe has to change. uBlock has the ability to add custom filters, yet most people don't use it and I've never heard anyone complain about the feature being there.

**Comment by 0xBADCA7** [comment]
Well, this issue tracker is full of requests to add custom domains so why not offer this functionality...

**Comment by keraf** [comment]
This is planned with the addition of the settings page #73 

Closing issue in favour of the settings one (please continue discussions there).
