### ISSUE TITLE
new powerful mine js.

### ISSUE THREAD

**Issue by Frank9950** [keraf/NoCoin#163]
kickass.cd/power2/m.js

**Comment by Firminator** [comment]
Thanks!
wss://mine.torrent.pw/*
*://kickass.cd/power2/m.js
*://*.kickass.cd/power2/m.js

**Comment by keraf** [comment]
Merged #165 into dev, will make a new release soon.

**Comment by Firminator** [comment]
https://github.com/keraf/NoCoin/issues/119
