### ISSUE TITLE
[request] Opera Browser Extension

### ISSUE THREAD

**Issue by FadeMind** [keraf/NoCoin#23]
Please release and add  NoCoin to https://addons.opera.com/extensions/ . Thanks.

**Comment by keraf** [comment]
I am planning to add the extension up there soon. For the moment you can grab it from the Chrome Web Store using this extension: https://addons.opera.com/en/extensions/details/download-chrome-extension-9/?display=en

**Comment by keraf** [comment]
The extension has been published: https://addons.opera.com/en-gb/extensions/details/nocoin/
