### ISSUE TITLE
Number of blocked scripts shown on extension icon

### ISSUE THREAD

**Issue by borekon** [keraf/NoCoin#27]
It woul be great if the app shows how many scripts are being blocked in the current website, similar as adblock does it.

**Comment by keraf** [comment]
I have thought of this but I don't think it is really relevant as there is usually only one miner per page. In the case of an adblocker for example, it would make more sense as a page usually has multiple ads on a page.

I have thought though about adding stats to the extension to see how many coin miners you blocked per day and per month. I would say it's a medium priority task, but definitely one for v1.0.

I'll leave this issue open for a day if you have any suggestions on how a counter for the current blocker script could be relevant for No Coin or further discussion on the coming stats feature.

**Comment by borekon** [comment]
Well, if not a counter, some stuff that shows that in the web page is a miner.
And any way to know if the current web page is already whitelisted.

--
Enviado desde la aplicación myMail para Android

jueves, 21 septiembre 2017, 08:06p. m. +02:00 de Rafael K notifications@github.com<mailto:notifications@github.com>:


I have thought of this but I don't think it is really relevant as there is usually only one miner per page. In the case of an adblocker for example, it would make more sense as a page usually has multiple ads on a page.

I have thought though about adding stats to the extension to see how many coin miners you blocked per day and per month. I would say it's a medium priority task, but definitely one for v1.0.

I'll leave this issue open for a day if you have any suggestions on how a counter for the current blocker script could be relevant for No Coin or further discussion on the coming stats feature.

**Comment by keraf** [comment]
Ah different states! This is planned for the next version (see issue #3). If you have further suggestions regarding this, please add them to the mentioned issue.
