### ISSUE TITLE
Different states

### ISSUE THREAD

**Issue by OZARIN** [keraf/NoCoin#3]
Suggest having four visibly identifiable states:

- no mining detected (enabled)
- no mining detected (disabled)
- mining detected (enabled)
- mining detected (disabled)

For the 'no mining detected' states, just use existing icons, but at lower opacity.

**Comment by keraf** [comment]
Thanks for the suggestion, I like the idea. I would even suggest having another state for whether the domain is white listed or not after #4 is implemented.

For the states, I would suggest:
- Enabled no mining detected: Simple coloured logo
- Disabled no mining detected: Simple gray scale logo
- Enabled mining detected and blocked: Coloured logo with red dot on the bottom right
- Enabled mining detected and white listed: Coloured logo with green dot on the bottom right
- Disabled mining detected: Gray scale logo with red dot logo on the bottom right.

Your opinion on the suggested states above is more than welcome.
