### ISSUE TITLE
Google Webstore - missing popup.js

### ISSUE THREAD

**Issue by eyJhb** [keraf/NoCoin#31]
I just installed this extension from the store 
https://chrome.google.com/webstore/detail/no-coin/gojamcfopckidlocpkbelmpjcgmbgjcl
But it doesn't include the popup.js.

**Comment by keraf** [comment]
Thanks for reporting this, I will look into this right now.

**Comment by keraf** [comment]
This was an issue with the build step. I published an update to the Chrome Web Store which should be available in the next hour and also submitted it on the Mozilla Add-On Store which should take about 24 hours to be available (if the submission is successful).

Could you please check if you have the update in an hour and confirm this is fixed? Thanks!

**Comment by keraf** [comment]
Passed 24 hours and reviewed by myself, this seems fixed. Please reopen an issue if there are any more problems. Cheers!
