### ISSUE TITLE
thanks to no coin, ive been taken for 300ksat 

### ISSUE THREAD

**Issue by abvemining** [keraf/NoCoin#43]
i'm running a faucet centered around people agreeing to mine before claiming my faucet, basically insuring the next person is able to claim my faucet without having to lock users out for ridiculous amounts of time or give absolutely terrible rewards. last night several no coin users were able to claim my faucet without mining and essentially emptied out my faucet. without giving back anything in return. i need a way to stop no coin users from accessing my site. or else no one is going to be able to benefit from my faucet  currently i have users mine for a set amount of hashes based on the exchange rate and costs associated with the money transfer fees(basically works our to 1sat given = 3 mined (1 given/1recieved/1tax). while allowing users who have access to large amounts of hash power to claim more frequently.  when using your app they are able to ignore this and claim as fast as one could solve a captcha  all while not supporting the site.. if there is any way i can stop users from accessing my site it would be much appreciated, i have no problems with no coin besides the fact that its going to force me to have to run a ad filled popup powered scammy looking faucet or no faucet at all if i cant stop people from abusing it by not participating in my mining captcha.

**Comment by Firminator** [comment]
Not sure why it would be necessary to run ads and popups on your faucet site. Why would anyone need to pay your costs? Odd business model.

**Comment by abvemining** [comment]
thats always been the deal with any faucet, your traffic through viewing the website and interacting with the ads was the value you recieved from the faucet. one does not just give away money for free.

**Comment by abvemining** [comment]
youtube and facebook are not free services even though they do not charge. they use your traffic and information to place highly effective ads in your face to then cover the costs of running the site and pay the workers. what my mining captcha allows for is essentially youtoube red to youtube.  if you agree to pay a set fee i can let you bypass all ads for a set period. but i don't have to charge. i just lock feature behind mining captcha  that sustainably ensures for any one use of faucet there will be another. and this process wont be hindered by me having to put my own personal money into faucet. pretty much a never ending faucet. that is "free" to all users

**Comment by abvemining** [comment]
the ads from you tube and Facebook in my case would be equivalent to the period of time i must make you wait to claim faucet again

**Comment by keraf** [comment]
Sorry to hear No Coin is causing you trouble. 

I guess you can probably tie the mining to a user by using this: https://coinhive.com/documentation/miner#coinhive-user

This way you could know if a user actually mined for you before rewarding him.
