### ISSUE TITLE
Does not block Crypto-Loot miner

### ISSUE THREAD

**Issue by BadPackets** [keraf/NoCoin#47]
[Crypto-Loot](https://crypto-loot.com/) is a brand new JavaScript miner similar to Coinhive.

Example site: http://www.ilovebicycling.com

<script src="https://crypto-loot.com/lib/miner.min.js"></script>
![new cryptojacker](https://user-images.githubusercontent.com/32589462/31305729-903cd1c8-aaf5-11e7-8d34-7b2bf9239e23.png)

**Comment by keraf** [comment]
Thanks for reporting this. I will push an update of the blacklist later today.

**Comment by keraf** [comment]
Blacklist has been updated and a new version pushed to all platforms. Thanks again for reporting this.

**Comment by BadPackets** [comment]
Confirmed, thanks!
