### ISSUE TITLE
New urls :)

### ISSUE THREAD

**Issue by ZeroDot1** [keraf/NoCoin#51]
```
*://*.edgeno.de/*
*://*.reasedoper.pw/*
*://*.jyhfuqoh.info/*
*://*.minemytraffic.com/lib*
```

**Comment by ZeroDot1** [comment]
gus.host
miner.pr0gramm.com
ppoi.org
projectpoi.com
kisshentai.net
xbasfbno.info
azvjudwr.info
jroqvbvw.info
jyhfuqoh.info
kdowqlpt.info
cnhv.co
2giga.link
jsecoin.com
load.jsecoin.com
server.jsecoin.com
load.jsecoin.com
static.reasedoper.pw
mataharirama.xyz
listat.biz
lmodr.biz
minecrunch.co
minemytraffic.com
crypto-loot.com
coinhive.com
coin-hive.com
edgeno.de
reasedoper.pw
jyhfuqoh.info
minemytraffic.com

**Comment by Emilylove00** [comment]
2giga.link
azvjudwr.info
cnhv.co
coinhive.com
coin-hive.com
crypto-loot.com
edgeno.de
gus.host
jroqvbvw.info
jsecoin.com
jyhfuqoh.info
kdowqlpt.info
listat.biz
lmodr.biz
mataharirama.xyz
minecrunch.co
minemytraffic.com
ppoi.org
pr0gramm.com
reasedoper.pw
xbasfbno.info

**Comment by Leondthurrell** [comment]
Thank you for the dump. I will go through these and take a look for miners and see if they are already caught by our current blacklist or not.

Some of these I know are already on the blacklist.

**Comment by Leondthurrell** [comment]
I will update this as I go through the list of sites and then will submit a PR with the updated blacklist
**Already Handled**
---

- [x] cnhv.co - whitelisted
- [x] jsecoin.com - Already on blacklist
- [x] load.jsecoin.com - Already on blacklist
- [x] server.jsecoin.com - Already on blacklist
- [x] static.reasedoper.pw - Already on blacklist
- [x] mataharirama.xyz - Already on blacklist
- [x] listat.biz - Already on blacklist
- [x] lmodr.biz - Already on blacklist
- [x] minecrunch.co - Already on blacklist
- [x] minemytraffic.com - Already on blacklist
- [x] crypto-loot.com - Already on blacklist
- [x] coinhive.com - already blacklisted
- [x] coin-hive.com - already blacklisted

**No miner found**
---

- [x] gus.host - no miner found


**Miner found rule created**
---

- [x] ppoi.org - rule created 
```
*://ppoi.org/lib/*
*://*.ppoi.org/lib/*
*://*.ppoi.org/token/*
```

- [x] 2giga.link - already on blacklist (added another URL) 

```
*://*.2giga.link/hive/lib/*
```

**Miner found no rule created (yet)**
---

- [ ] miner.pr0gramm.com - self hosted miner and only on a section of their site spefically for mining

**Not checked**
---

- [ ] projectpoi.com
- [ ] kisshentai.net
- [ ] xbasfbno.info
- [ ] azvjudwr.info
- [ ] jroqvbvw.info
- [ ] jyhfuqoh.info
- [ ] kdowqlpt.info
- [ ] edgeno.de 
- [ ] jyhfuqoh.info

**Comment by ZeroDot1** [comment]
https://gus.host/coins.js

**Comment by ZeroDot1** [comment]
I hope I was able to help improve the addon a little bit, because this coin mining is theft, they steal the money from our wallet in the long run, because we have to pay the users of a computer for higher electricity costs.

**Comment by ZeroDot1** [comment]
http://miner.pr0gramm.com/cryptonight-worker.js

**Comment by ZeroDot1** [comment]
http://kisshentai.net/Content/js/c-hive.js

**Comment by ZeroDot1** [comment]
https://crypto-loot.com/lib/miner.min.js

**Comment by keraf** [comment]
Thanks all for your work, this is now live on all platforms (Chrome, Firefox and Opera). I also added miner.pr0gramm.com to the mix btw.

**Comment by ZeroDot1** [comment]
https://minecrunch.co/web/miner.js
http://kukunin.github.io/webminer/

**Comment by ZeroDot1** [comment]
```
xmrpool.eu
moneropool.com
monero.crypto-pool.fr
monerohash.com
minexmr.com
usxmrpool.com
supportxmr.com
moneroocean.stream
minemonero.pro
xmr.prohash.net
minercircle.com
poolmining.org
xmr.nanopool.org
xmrminerpro.com
```

**Comment by ZeroDot1** [comment]
CoinBlockerList: https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt

**Comment by mastad0n** [comment]
https://github.com/hoshsadiq/adblock-nocoin-list/issues/53
