### ISSUE TITLE
white list permanently not working

### ISSUE THREAD

**Issue by hworm4** [keraf/NoCoin#52]

**Comment by keraf** [comment]
What browser are you using? I see that it is not possible to white list any more in Opera 48 but it is working in Chrome 61.

**Comment by hworm4** [comment]
actually my browser is Chrome 61.

**Comment by keraf** [comment]
Could you provide more specific information (see https://github.com/keraf/NoCoin/wiki/Bugs) as well as the exact browser version please?

**Comment by keraf** [comment]
I think I found out why it wasn't working. My adblocker is already blacklisting coin miners and kicked in before No Coin, so therefore there's nothing to black/white list for No Coin... Try disabling your AdBlocker for testing if you have one and let me know if that solves the issue.

**Comment by hworm4** [comment]
Reproduction steps:
1- go to any website
2- white list it permanently
3- refresh website or navigate to another page
Browser with version
Operating system
NoCoin version

**Comment by hworm4** [comment]
Reproduction steps:
1- go to any website
2- white list it permanently
3- refresh website or navigate to another page
4- website still black listed
Browser with version: 61.0.3163.100 (Official Build) (64-bit)
Operating system: windows 10 
NoCoin version 0.4.2

**Comment by Sajo811** [comment]
I'm getting the same problem.
Reproduction steps-
1. Go to any website
2. Choose to whitelist it permanently.
3. click off
4. Still blacklisted
ex- coinhive.com Unable to load the front page miner
Browser- Firefox 57.0b12 x64
Also doesn't work on stable builds.
Extensions- Ghostery, Ublock and NoCoin
x64 Win 7 Ultimate(doesn't work on win 10 x64)

I disabled ublock and no coin, still doesn't work. Please fix dis. :|

**Comment by keraf** [comment]
Strange, I still can't reproduce this. Everything is working as expected across the browsers (Opera, Chrome, Chromium, Firefox, FF Dev, Nightly) and OS (Windows 10 & Ubuntu 17.10) I tested No Coin on. My guess would be that something is interfering with No Coin because those are the only issues I had when using Opera along with its built-in adblocker.

**Comment by Firminator** [comment]
Can be closed right?

**Comment by keraf** [comment]
@Firminator Yeah I guess so. If the issue persists, please open a new issue.
