### ISSUE TITLE
Block coinerra

### ISSUE THREAD

**Issue by aloisdg** [keraf/NoCoin#53]
Coinera, an alternative to coinhive: https://coinerra.com/

[HN discussion](https://news.ycombinator.com/item?id=15457327)

**Comment by keraf** [comment]
Thanks for reporting this one, I have a rule coming soon.

**Comment by keraf** [comment]
This is now live on all platforms (Chrome, Firefox and Opera)

**Comment by aloisdg** [comment]
Thank you
