### ISSUE TITLE
Block hashforcash.us & coin-have.com

### ISSUE THREAD

**Issue by ZeroDot1** [keraf/NoCoin#54]
```
http://www.hashforcash.us/
https://coin-have.com/
```

**Comment by keraf** [comment]
Thanks for reporting those new services. Hash for cash looks to still be in construction, do you have an example of it being used somewhere?

And I have a rule for coin-have coming soon.

**Comment by keraf** [comment]
Rule for coin-have is live. Keeping this issue open for the update on hashforcash.

**Comment by ZeroDot1** [comment]
I found www.hashforcash.us here: http://coinpress.info/coinhive-alternatives/
