### ISSUE TITLE
Replace blocked Coinhive Captcha by an image

### ISSUE THREAD

**Issue by keraf** [keraf/NoCoin#6]
To make users aware that the Coinhive captcha has been blocked, it should ideally be replaced by a similar size image and ideally with the possibility to click on it to temporarily allow it.

**Comment by albinekb** [comment]
An improvement of this would be an option to allow the captchas but disallow all other kinds of mining.

**Comment by keraf** [comment]
Captcha's are mining with consent and will be placed in a strict blacklist for the user to enable or not in v1.0 (currently in progress, will be (hopefully) released this month). Closing issue.
