### ISSUE TITLE
Block coinblind.com & coinnebula.com

### ISSUE THREAD

**Issue by georgeescott** [keraf/NoCoin#63]
Microsoft Malware Protection Center have detected CoinBlind embedded in possibly compromised websites. More info here: https://twitter.com/msftmmpc/status/920462009958850560.

**Comment by georgeescott** [comment]
Looks like they've also detected coinnebula.com - https://twitter.com/msftmmpc/status/919831580184645632.

**Comment by Firminator** [comment]
Here's are two sources to see CoinBlind in action:
- capodannoinversilia.com
- versiliaguide.com

**Comment by Firminator** [comment]
Can't find anything for coinnebula.com, please provide example.

**Comment by georgeescott** [comment]
Couldnt find any sites using it, but found the script it uses instead: https://coinnebula.com/lib/coinnebula.min.js.

**Comment by keraf** [comment]
Thanks for the report, I will look into this shortly.

**Comment by keraf** [comment]
Merged PR #65 and #66 - they should block those once I merge to master. Thanks @Firminator for those PRs!

**Comment by jeflopo** [comment]
@georgeescott This site uses coinnebula https://povw1deo.com/embed-xfjug8u6790j.html (It's Powvideo site, homeland 7x11)

`var iner = new CoinNebula.Instance('\x70\x6f\x77\x76\x69\x64\x65\x6f\x2e\x6e\x65\x74', {throttle: 0.7}); if(!iner.isMobile()) iner.start();`
