### ISSUE TITLE
Block webmine.cz

### ISSUE THREAD

**Issue by ZeroDot1** [keraf/NoCoin#69]
`://*.webmine.cz/miner`

**Comment by keraf** [comment]
Same comment as in #67

**Comment by gwarser** [comment]
@keraf they authed miner is served from `https://authedwebmine.cz/authedminer.js` 
`webmine.cz/miner` is not asking for consent.

**Comment by Firminator** [comment]
Weird. How is this possible?

**Comment by keraf** [comment]
Thanks guys, I'll add this one to the blacklist.

**Comment by keraf** [comment]
That's now blocked (see #74). Closing issue.
