### ISSUE TITLE
"Settings" are not active

### ISSUE THREAD

**Issue by erikaflynn** [keraf/NoCoin#72]
I can only "Pause" No coin and "Resume" no coin or add current site to whitelist. No any other features, no SETTINGS. How will I know that it is working? How can I see or redact my whitelist?

**Comment by keraf** [comment]
There are plans to have a settings page to manage the blacklist and whitelist. Unfortunately I'm quite busy at the moment and didn't get around it. Feel free to work on a PR if you feel like it.

For now, the way to add/remove domains to your whitelist is by visiting them.

I made a new issue for this and will close this one - see #73
