### ISSUE TITLE
block Hi10Anime.com

### ISSUE THREAD

**Issue by SonicBlader** [keraf/NoCoin#75]
Hi10anime.com

**Comment by ZeroDot1** [comment]
```
www.hi10anime.com
web.hi10anime.com

```

**Comment by keraf** [comment]
I just checked the website but can't see any mining going on. Could you point me on what makes you think it's mining?

**Comment by Firminator** [comment]
Just checked again and found no mining. Website is also out-of-date it seems. I would close issue until someone spots mining again, then it can be investigated from where it stems from.
