### ISSUE TITLE
Block monerominer.rocks

### ISSUE THREAD

**Issue by ZeroDot1** [keraf/NoCoin#76]
```
monerominer.rocks
admin.monerominer.rocks
mail.monerominer.rocks
```
`http://monerominer.rocks/scripts/miner.js`
https://www.virustotal.com/#/url/da98b206e9f5db488488f5474549770d3c361c6ef963fea65707421a1a677a34/detection

**Comment by keraf** [comment]
Thanks for reporting it, I will add it shorty to the blacklist.

**Comment by ZeroDot1** [comment]
Thank you:)
