### ISSUE TITLE
Block cloudcoins.co

### ISSUE THREAD

**Issue by jvanoeffel** [keraf/NoCoin#77]
Can you also block cloudcoins.co

cdn.cloudcoins.co/javascript/cloudcoins.min.js

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/issues/22

**Comment by keraf** [comment]
Thanks for reporting this one, going to be on the blacklist shortly.

**Comment by ZeroDot1** [comment]
Thank you:)
