### ISSUE TITLE
Possible crypto miner on TrustedReviews site

### ISSUE THREAD

**Issue by codefl0w** [keraf/NoCoin#80]
http://www.trustedreviews.com/news/ps4-pro-vs-ps4-2941086

When I visit this link, it causes a massive CPU spike (+10%) for 10+ seconds followed by a constant 1%-2% load by one of Chrome's processes (normally at 0.1% load). The site is also extremely unresponsive.

PC specs: Intel 5820K @ 4.4 GHz, 16 GB RAM, Evga GTX 670 ... a 10% spike is MASSIVE for this website

**Comment by keraf** [comment]
It looks more like a poorly written website to me and it doesn't look like it's mining. Are there any mining scripts you spotted?
