### ISSUE TITLE
NoCoin icon is GIANT in FF

### ISSUE THREAD

**Issue by andyross63** [keraf/NoCoin#81]
Running FF 56.0.2 under Windows 10. For some reason, the NoCoin icon is HUGE. What is going on? This makes it more or less unusable.
![nocoin](https://user-images.githubusercontent.com/33353167/32381106-e3b9c802-c07f-11e7-8030-533fb31de59c.jpg)

**Comment by keraf** [comment]
I updated Firefox to 56.0.2 and I'm running it on Windows 10, everything looks fine to me but strangely my browser does not look like yours. Do you have a custom theme or visual settings? If yes, could you please share them here.

**Comment by andyross63** [comment]
I tracked this down to Classic Theme Restorer (which will be unusable with FF57 anyways.) The Toolbars/Page 1 setting for "Navigation toolbar attribute 'iconsize'" was set to "large icons" instead of "small icons." This is the first app I've seen that was affected by it, as everything else was already small as selected from the standard FF customize screen.

**Comment by AlexandreBonneau** [comment]
For info, the icon size is ok under FF `58.0b12`.

**Comment by LYTzeng** [comment]
The icon size looks fine in FF 58.
