### ISSUE TITLE
Add to blacklist

### ISSUE THREAD

**Issue by phr34k0** [keraf/NoCoin#83]
![screenshot_20171105-100258](https://user-images.githubusercontent.com/13272249/32420686-23f5698a-c2c9-11e7-81cc-17dd4b3de8fa.png)

Add these to blacklist thanks!

**Comment by ZeroDot1** [comment]
@phr34k0 For Android you can use the CoinBlockerLists. 
https://github.com/ZeroDot1/CoinBlockerLists

**Comment by phr34k0** [comment]
@ZeroDot1 Thanks but no, I'd rather do my own strings of regex or pipe it through my own DNS server. Nothing to do with Android lol
