### ISSUE TITLE
NoCoin v0.4.7 can't stop coinhive in google / youtube websites.

### ISSUE THREAD

**Issue by innocentliny** [keraf/NoCoin#89]
Hi,

NoCoin seems not working to block coinhive in google / youtube websites,
It should work, maybe I misunderstand something.

- Reproduction steps:
  1. Install Wappalyzer chrome plugin.
  2. Go to https://www.google.com or https://www.youtube.com.
  3. Click Wappalyzer icon, it will show website is using coinhive.
  4. NoCoin doesn't show alert mark.
 
- Browser with exact version: Chrome 62.0.3202.89 (64 bits)
- Currently enabled extensions in your browser:
  >Adguard 2.7.2
Dark Reader 3.5.0
Enable Copy 1.17
No Coin - Block miners on the web! 0.4.7
OneTab 1.18
Stylish 1.8.2
Wappalyzer 5.1.5

- Operating system: Win7 Pro 64 bits
- NoCoin version: 0.4.7
- Screenshot, gif or video
  >![image](https://user-images.githubusercontent.com/5312376/32590488-93bd7d00-c555-11e7-9ae7-c905ff5dbc44.png)

Thank you.

**Comment by gadcam** [comment]
It is not related with NoCoin : you should update the list of Adguard. See https://github.com/AliasIO/Wappalyzer/issues/1807

**Comment by Firminator** [comment]
Yes, thanks for pointing this out. Issue can be closed.
