### ISSUE TITLE
Block JSEcoin

### ISSUE THREAD

**Issue by keraf** [keraf/NoCoin#9]
Someone Tweeted at me that there's another coin mining service named JSEcoin. Should have a look into adding that one to the blacklist too

Link: https://jsecoin.com

**Comment by arthurgeron** [comment]
# #17

**Comment by arthurgeron** [comment]
#17 Added jsecoin to blacklist

**Comment by Emilylove00** [comment]
I just downloaded this extension thanks you @arthurgeron for your great work!!!

**Comment by keraf** [comment]
This has been added to the blacklist. Closing.
