### ISSUE TITLE
rocks.io miner

### ISSUE THREAD

**Issue by ryanbr** [keraf/NoCoin#92]
Just added to Easyprivacy;

https://github.com/easylist/easylist/commit/dd3ebd20ae5c9e3e2cfd119c8229b24a166ff834

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists/issues/54

**Comment by ZeroDot1** [comment]
```
*://*.rocks.io/*
*://*.rocks.io/assets/rocks.min.js*
```

**Comment by Firminator** [comment]
source: https://www.rocks.io/assets/rocks.min.js

Shards:
"wss://ws-ca-01.rocks.io/proxy"
"wss://ws-fr-01.rocks.io/proxy"
"wss://ws-fr-02.rocks.io/proxy"
"wss://ws-fr-03.rocks.io/proxy"
"wss://ws-de-01.rocks.io/proxy"
"wss://ws-de-02.rocks.io/proxy"
"wss://ws-de-03.rocks.io/proxy"
"wss://ws-de-04.rocks.io/proxy"
"wss://ws-de-05.rocks.io/proxy"

**Comment by keraf** [comment]
Fixed with PR #96 (thanks @Firminator )
