### ISSUE TITLE
Block cookiescript.info

### ISSUE THREAD

**Issue by ZeroDot1** [keraf/NoCoin#94]
https://github.com/ZeroDot1/CoinBlockerLists/issues/59

```
http://cookiescript.info/libs/cookiescript.min.js
http://cookiescript.info/libs/cookiescrip.min.js
http://cdn.cookiescript.info/libs/cookiescript.min.js
http://cdn.cookiescript.info/libs/cookiescrip.min.js
```

https://www.virustotal.com/de/file/2f6b4879b907d0ed73bd6e718296de9a349a2e41b8de5e469f9cf3cf3b8cd0d4/analysis/

**Comment by Firminator** [comment]
Are you saying that CookieScript.info has been hacked and the miscreants replaced the legit cookiescript.min.js with one that mines cryptocurrency?

**Comment by ZeroDot1** [comment]
@Firminator 
I don't know, I noticed it just when I was looking for mining scripts.

**Comment by Firminator** [comment]
tag Need more info

**Comment by Firminator** [comment]
http://cookiescript.info/libs/cookiescrip.min.js doesn't exist.
http://cookiescript.info/libs/cookiescript.min.js shows wss://ws01.crypto-loot.com/proxy which is already blocked by NoCoin.

The original file is http://cookiescript.info/libs/cookiescript.original.js

http://cookiescript.info/libs/ shows all files. There are more libs hacked. A total of 5:
http://cookiescript.info/libs/cookieconsent.4.min.js
http://cookiescript.info/libs/cookieconsent.5.min.js
http://cookiescript.info/libs/cookieconsent.6.min.js
http://cookiescript.info/libs/cookiescript.min.2.js
http://cookiescript.info/libs/cookiescript.min.js


This website is either hacked with cryptomining code put literally above the original script code or it's a website that was designed to lure people into trusting it and adding malcode later. Whois shows good old Panama.

Going to add block.

**Comment by Firminator** [comment]
Files are http://cdn.cookiescript.info/libs/ are duplicated of http://cookiescript.info/libs/

**Comment by keraf** [comment]
Comment from #97 

> Not sure if it's intentional but I'll still block it for now. Will contact the domain owner to get back in touch with me once it's removed. There's also cookiescriptcdn.pro. I'm going to add that one after merging your change.
