### ISSUE TITLE
Removed from Firefox addons

### ISSUE THREAD

**Issue by xopez** [keraf/NoCoin#98]
Why got it removed from firefox addons?
https://addons.mozilla.org/de/firefox/addon/no-coin/

Message:
Page not found

Sorry, but we can't find anything at the address you entered.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

**Comment by keraf** [comment]
Hi there,

The extension got removed because it didn't pass the latest submission. I will resubmit the package tonight. and hopefully it will be back there shortly

**Comment by keraf** [comment]
The extension passed the submission and is now back on the Mozilla Addons store 😄
